QuickGuide/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^/?$', views.index, name='index'),
    url(r'/results/?$', views.results, name='results'),
]

QuickGuideSite/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^QuickGuide', include('QuickGuide.urls', namespace="QuickGuide")),
]

QuickGuide/models.py
from django.db import models

# Create your models here.

QuickGuide/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
import extractText_teaser as ett
from django.template import RequestContext, loader

# Create your views here.
def index(request):
    return render(request, 'QuickGuide/index.html')

def ask(request):
	if request.method == 'POST':
		form = request.POST
		print "Response is post"

		return HttpResponseRedirect('results/')
	else:
		print "response is not post"
		form= nameForm()

	return render(request, 'QuickGuide/index.html', {
            'error_message': "You didn't enter a query",
            })

def results(request):

	if request.method == 'POST':
		rqst = request.POST.get("Query")
		if not rqst:
			return render(request, 'QuickGuide/index.html', {
            'error_message': "You didn't enter a query",
            })
		# run algorithm
		shortsummary = ett.shortSummaryFromQuery(rqst)
		tmp=""
		for sentence in shortsummary:
			tmp = tmp+" "+sentence
		shortsummary = tmp
		tmp=""

		longSummary = ett.longSummaryFromQuery(rqst)
		for sentence in longSummary:
			tmp = tmp+" "+sentence
		longSummary = tmp
		tmp=""

		wholeArcticle = ett.wholeArticleFromQuery(rqst)
		for sentence in wholeArcticle:
			tmp = tmp+" "+sentence
		wholeArcticle = tmp
		# page_summaries_list = [request.POST.get("Query"),"shortsummary","longSummary","wholeArcticle"]
		page_summaries_list = [request.POST.get("Query"),shortsummary,longSummary,wholeArcticle]

		context = {'page_summaries_list': page_summaries_list}

		return render(request, 'QuickGuide/results.html', context)

		

QuickGuide/templates/QuickGuide/index.html
{%load staticfiles%}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="../../favicon.ico">

	<title>Fixed Top Navbar Example for Bootstrap</title>

	<!-- Bootstrap core CSS -->
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:100,400,500,700' rel='stylesheet' type='text/css'>
	<!-- Custom styles for this template -->
	<link href="navbar-fixed-top.css" rel="stylesheet">
	<style type="text/css">body {
		min-height: 2000px;
		padding-top: 140px;
		}</style>

		<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
		<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
		<script src="../../assets/js/ie-emulation-modes-warning.js"></script>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>

  <body>

  	<!-- Fixed navbar -->
  	<nav class="navbar navbar-default navbar-fixed-top">
  		<div class="container">
  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
  					<span class="sr-only">Toggle navigation</span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</button>
  				<a class="navbar-brand" href="/QuickGuide">Quick Guide</a>
  			</div>
  			<div id="navbar" class="navbar-collapse collapse">
  				<ul class="nav navbar-nav">
  					<li class="active"><a href="/QuickGuide">Home</a></li>
  					<li><a href="#about">About</a></li>
  				</ul>
  			</div><!--/.nav-collapse -->
  		</div>
  	</nav>

  	<div class="container">

  		<!-- Main component for a primary marketing message or call to action -->
  		<div class="jumbotron">
  			<h1>Quick Guide</h1>
  			<form action="{% url 'QuickGuide:results' %}" method="post">
  				{% csrf_token %}
  				<input type="text" name="Query" />
  				<!-- <input type="submit" value="Go!" /> -->
  				<br> <br>
  				<input class="btn btn-lg btn-primary" type="submit" value="Go! &raquo;" />
  			</form>
  			
  		</p>
  	</div>

  </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

QuickGuide/templates/QuickGuide/results.html
{%load staticfiles%}
<html>
<head>
	<title>Bernoulli | Math reimagined.</title>
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:100,400,500,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		padding-top: 50px;
	}
	.starter-template {
		padding: 40px 15px;
		text-align: center;
	}
	</style>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/QuickGuide">Quick Guide</a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="/QuickGuide">Home</a></li>
						<li><a href="#about">About</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">

			<div class="starter-template">
				<h1>{{ page_summaries_list.0 }}</h1>
				<h2>Short Summary</h2>
				<p class="lead">{{ page_summaries_list.1 }}<br>
					{% if page_summaries_list.1 != page_summaries_list.2 %}
					<h2>Long Summary</h2>
					{{ page_summaries_list.2 }}</p>
					{% endif %}
					{% if page_summaries_list.2 != page_summaries_list.3 %}
					<h2>Whole Article</h3>
						{{ page_summaries_list.3 }}
					{% endif %}
					</div>
				</body>
				</html>